### ISSUE TITLE
Direct shooting

### ISSUE THREAD

**Issue by control-toolbox** [control-toolbox/CTDirectShooting.jl#2]
- [ ] pouvoir choisir l'intégrateur et la taille de la sous-grille si on utilise du pas fixe, sinon les tolérances.
- [ ] ~~ajouter cpu time~~
- [ ] revoir les plots pour gérer mieux quand y'aura d'autres solveurs.
- [ ] a voir si le comportement par défaut de `plot(ocp, :time, :state)` ne serait pas d'afficher tous les states.
- [ ] ~~ajouter `interpolation` + `approche finition`.~~
- [ ] généraliser le problème de contrôle que l'on peut résoudre et généraliser le calcul de l'adjoint, qui est ici explicite mais qui pourrait être implicite dans certains cas plus difficile, par exemple si on a des contraintes qui mélangent $x_0$ et $x_f$.

**Comment by ocots** [comment]
Pouvoir choisir une grille en $x$.

**Comment by ocots** [comment]
Plus généralement, il faut voir comment on gère la transcription d'un problème à partir d'un choix d'algorithme et la gestion de la solution. A-t-on un type de solution dépendant du type de problème, de la paire problème-algo ou autre chose ? Voir [issue 12](https://github.com/control-toolbox/control-toolbox.github.io/issues/12).

**Comment by ocots** [comment]
Unifier `OptimalControlModel` et `OptimalControlProblem`.

**Comment by ocots** [comment]
Voir aussi [Issue 23](https://github.com/control-toolbox/OptimalControl.jl/issues/23).
